--CREATE DATABASE KOLSAN



-- MÜÞTERÝ TABLOSU
/*CREATE TABLE K_CUSTOMER(
LOGREF INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
TC CHAR(11)  NOT NULL,
FIRST_NAME VARCHAR(30) NOT NULL,
SURNAME VARCHAR(30) NOT NULL,
NUMBER CHAR(10) NOT NULL,
MAIL VARCHAR(25),
DATE_OF_BIRTH DATE,
CITY VARCHAR(15),
OPEN_ADDRESS VARCHAR(150)
)
INSERT INTO K_CUSTOMER(TC, FIRST_NAME, SURNAME, NUMBER, MAIL, DATE_OF_BIRTH, CITY, OPEN_ADDRESS) VALUES ('12698514581','Ali','Yýlmaz','5012346789','ali123@gmail.com','1998.07.08','Bartýn','Kemerköprü Mahallesi No:19')
INSERT INTO K_CUSTOMER(TC, FIRST_NAME, SURNAME, NUMBER, MAIL, DATE_OF_BIRTH, CITY, OPEN_ADDRESS) VALUES ('35877423258','Ayþe','Demir','5436789012','ayse.d@gmail.com','1999.11.03','Ýstanbul','Osmanlý Sokak No:6')
INSERT INTO K_CUSTOMER(TC, FIRST_NAME, SURNAME, NUMBER, MAIL, DATE_OF_BIRTH, CITY, OPEN_ADDRESS) VALUES ('74185296381','Mehmet','Çelik','5443120987','celikm@gmail.com','2000.03.21','Mersin','Mutlu Sokak No:7')
INSERT INTO K_CUSTOMER(TC, FIRST_NAME, SURNAME, NUMBER, MAIL, DATE_OF_BIRTH, CITY, OPEN_ADDRESS) VALUES ('14725836912','Elif','Arslan','5397618515','a.elif@gmail.com','1985.09.18','Erzurum','Yeniköy Mahallesi No:21')
INSERT INTO K_CUSTOMER(TC, FIRST_NAME, SURNAME, NUMBER, MAIL, DATE_OF_BIRTH, CITY, OPEN_ADDRESS) VALUES ('32165498715','Oðuzhan','Kaya','5361319333','oguzkaya@gmail.com','1993.12.14','Sivas','Çiçek Sokak  No:23')
INSERT INTO K_CUSTOMER(TC, FIRST_NAME, SURNAME, NUMBER, MAIL, DATE_OF_BIRTH, CITY, OPEN_ADDRESS) VALUES ('90132475680','Zeynep','Polat','5353156515','polatzey@gmail.com','2001.09.19','Ýzmir','Orman Sokak no:5')
INSERT INTO K_CUSTOMER(TC, FIRST_NAME, SURNAME, NUMBER, MAIL, DATE_OF_BIRTH, CITY, OPEN_ADDRESS) VALUES ('56497326585','Canan','Öztürk','5379154985','coztur@gmail.com','1997.12.21','Ankara','Yeþilbahçe Sokak no:3')
INSERT INTO K_CUSTOMER(TC, FIRST_NAME, SURNAME, NUMBER, MAIL, DATE_OF_BIRTH, CITY, OPEN_ADDRESS) VALUES ('38171468551','Efe','Koç','5387712815','kocefe@gmail.com','2002.10.15','Samsun','Huzur Caddesi 27. sokak')
INSERT INTO K_CUSTOMER(TC, FIRST_NAME, SURNAME, NUMBER, MAIL, DATE_OF_BIRTH, CITY, OPEN_ADDRESS) VALUES ('26831486179','Merve','Aydýn','5319125614','aydinmerve@gmail.com','2000.01.09','Karabük','Esmer Sokak No:13')
*/



-- ÜRÜN TABLOSU
/*CREATE TABLE K_PRODUCT(
LOGREF INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
MODEL VARCHAR(40),
CATEGORY VARCHAR(40),
TYPEE VARCHAR(40),
DIMENSION VARCHAR(40),
COLOUR VARCHAR(30),
PIECE_PRICE INT,
STOCK INT 
)

INSERT INTO K_PRODUCT(MODEL,CATEGORY,TYPEE,DIMENSION,COLOUR,PIECE_PRICE,STOCK) VALUES ('MODEL1','YEMEK','AHÞAP','47X86','SÝYAH','8500','10')
INSERT INTO K_PRODUCT(MODEL,CATEGORY,TYPEE,DIMENSION,COLOUR,PIECE_PRICE,STOCK) VALUES ('MODEL2','MUTFAK','METAL','50X90','ACI KAHVE','9000','50')
INSERT INTO K_PRODUCT(MODEL,CATEGORY,TYPEE,DIMENSION,COLOUR,PIECE_PRICE,STOCK) VALUES ('MODEL3','SALON','DEMÝR','45X150','KAHVERENGÝ','7500','35')
INSERT INTO K_PRODUCT(MODEL,CATEGORY,TYPEE,DIMENSION,COLOUR,PIECE_PRICE,STOCK) VALUES ('MODEL4','BAR','TEL','60X92','MOR','10000','70')
INSERT INTO K_PRODUCT(MODEL,CATEGORY,TYPEE,DIMENSION,COLOUR,PIECE_PRICE,STOCK) VALUES ('MODEL5','MUTFAK','KETEN','40X50','MAVÝ','6000','60')
INSERT INTO K_PRODUCT(MODEL,CATEGORY,TYPEE,DIMENSION,COLOUR,PIECE_PRICE,STOCK) VALUES ('MODEL6','BÜRO','DERÝ','48X92','YEÞÝL','7000','90')
INSERT INTO K_PRODUCT(MODEL,CATEGORY,TYPEE,DIMENSION,COLOUR,PIECE_PRICE,STOCK) VALUES ('MODEL7','ORGANÝZASYON','VÝNA','120X45','BEJ','3000','150')
INSERT INTO K_PRODUCT(MODEL,CATEGORY,TYPEE,DIMENSION,COLOUR,PIECE_PRICE,STOCK) VALUES ('MODEL8','BENCH','PLASTÝK','50X82','GRÝ','4500','60')
INSERT INTO K_PRODUCT(MODEL,CATEGORY,TYPEE,DIMENSION,COLOUR,PIECE_PRICE,STOCK) VALUES ('MODEL9','PUF','PAMUKLU','46X90','KREM','8600','40')
INSERT INTO K_PRODUCT(MODEL,CATEGORY,TYPEE,DIMENSION,COLOUR,PIECE_PRICE,STOCK) VALUES ('MODEL10','TABURE','KAÞMÝR','60X90','PEMBE','9200','80')
INSERT INTO K_PRODUCT(MODEL,CATEGORY,TYPEE,DIMENSION,COLOUR,PIECE_PRICE,STOCK) VALUES ('MODEL11','RESTORAN','SETEN','43X89','TURUNCU','4800','60')
INSERT INTO K_PRODUCT(MODEL,CATEGORY,TYPEE,DIMENSION,COLOUR,PIECE_PRICE,STOCK) VALUES ('MODEL12','BAHÇE','HASIR','55X70','SARI','9500','150')
*/



/*
USE KOLSAN
CREATE TABLE K_SALES(
LOGREF INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
K_CUSTOMERLOGREF INT FOREIGN KEY REFERENCES K_CUSTOMER(LOGREF) NOT NULL,
K_PRODUCTLOGREF INT FOREIGN KEY REFERENCES K_PRODUCT(LOGREF) NOT NULL,
CREATE_DATE VARCHAR(50),
PIECE INT,--ADET
PIECE_PRICE INT, --ADET FIYATI
PRICE INT,--FÝYAT
DISCOUNT CHAR(4),
DEBT INT,
EMPLOYEE VARCHAR(40),
EXPLANATION VARCHAR(250)
)
*/
--Satýþ tabloduna veriler uygulama üzerinden eklemek daha düzgün çalýþmasýný saðlar